import Config

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# For development, we disable any cache and enable
# debugging and code reloading.
#

# Configure your database
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :lost_green, LostGreen.Repo,
  database: Path.expand("../lost_green_dev.db", __DIR__),
  pool_size: 5,
  stacktrace: true,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  show_sensitive_data_on_connection_error: true

config :lost_green, LostGreenWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "wvT6jNSrd6ef+sNx/labTimZXxLtoMtv5RXHfVkJeLwQaKI0DzvkoWzuoIivCm85",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:lost_green, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:lost_green, ~w(--watch)]}
  ]

# Reload browser tabs when matching files change.
config :lost_green, LostGreenWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    # ## SSL Support
    #
    patterns: [
      # Static assets, except user uploads
      # In order to use HTTPS in development, a self-signed
      # certificate can be generated by running the following
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      # Mix task:
      #
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      #     mix phx.gen.cert
      #
      # Run `mix help phx.gen.cert` for more information.
      #
      # The `http:` config above can be replaced with:
      #
      ~r"lib/lost_green_web/router\.ex$"E,
      ~r"lib/lost_green_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
config :lost_green, dev_routes: true

# Initialize plugs at runtime for faster development compilation
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# If desired, both `http:` and `https:` keys can be
# in production as building large stacktraces may be expensive.
# configured to run both http and https servers on
# different ports.
# Include debug annotations and locations in rendered markup.
# Changing this configuration will require mix clean and a full recompile.
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
